on:
  push:
    paths-ignore:
      - "*.md"
      - "docker-compose.yml"
      - "**.md"
      - "**.gitignore"

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_REPO: featheredtoast/discourse-db

jobs:
  push:
    if: (github.ref == 'refs/heads/main')
    environment: docker push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [13, 14, 15, 16, 17]
    env:
      LATEST: 17
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build images
        run: |
          docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ env.DOCKER_REPO }}:pg${{ matrix.version }} --build-arg VERSION=${{ matrix.version }} .
          docker push ${{ env.DOCKER_REPO }}:pg${{ matrix.version }}
          if [ "${{ matrix.version }}" = "${{ env.LATEST }}" ]; then
            docker tag ${{ env.DOCKER_REPO }}:pg${{ matrix.version }} ${{ env.DOCKER_REPO }}:latest
            docker push ${{ env.DOCKER_REPO }}:latest
          fi
