on:
  push:
    paths-ignore:
      - "*.md"
      - "docker-compose.yml"
      - "**.md"
      - "**.gitignore"

env:
  BUILDKIT_PROGRESS: plain

jobs:
  push:
    if: (github.ref == 'refs/heads/main')
    environment: docker push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [13, 14, 15, 16, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build images
        run: |
          docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag featheredtoast/discourse-db:pg${{ matrix.version }} --build-arg VERSION=${{ matrix.version }} .
