on:
  push:
    paths-ignore:
      - "*.md"
      - "docker-compose.yml"
      - "**.md"
      - "**.gitignore"
  schedule:
    - cron: "0 0 1 * *"

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_REPO: discourse/postgres

jobs:
  push:
    if: (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [13, 14, 15, 16, 17]
    env:
      LATEST: 15
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build images
        run: |
          docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag ${{ env.DOCKER_REPO }}:pg${{ matrix.version }} --build-arg VERSION=${{ matrix.version }} .
          if [ "${{ matrix.version }}" = "${{ env.LATEST }}" ]; then
            docker buildx build --push --platform linux/amd64,linux/arm64 --tag ${{ env.DOCKER_REPO }}:latest --build-arg VERSION=${{ matrix.version }} .
          fi
